### ISSUE TITLE
Using this in Objective-C?

### ISSUE THREAD

**Issue by 10000TB** [gonzalonunez/Skeleton#9]
Great work!!
Is there a example in demonstrating how to use this in Objective-C?

**Comment by gonzalonunez** [comment]
Thank you 🙂

Let me see if I can quickly port the existing Swift example app to Objective-C!

**Comment by gonzalonunez** [comment]
So, I hadn't realized that the `Direction` enum is not Obj-C compatible. I might rewrite some stuff in order to get it to work, but for now I suspect you can write only the logic related to Skeleton in Swift and expose it in a way that's compatible with Objective-C. How does this sound? Really sorry it's not compatible right out of the box 😣

**Comment by light-bo** [comment]
Look forward to Objective-C version of this lib. 😄

**Comment by mayqiyue** [comment]
Hey, thanks for the great library . And I wrote a ObjC Version.
https://github.com/mayqiyue/OCSkeleton
